FROM tensorflow/tensorflow:latest-py3-jupyter

ARG USERNAME=happy
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    git \    
    curl\
    nano\
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME  

WORKDIR /home/$USERNAME/app
    
COPY requirements.txt ./
COPY . /home/$USERNAME/app

RUN pip install --upgrade pip 
RUN pip install -r requirements.txt 

EXPOSE 8888
